name: apegram
favicon: null
layout_spectrum: 0.40564508899115026
typography_spectrum: 0.8223053575493395
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.11104182316921651
  lightness: 0.24511955422349274
  saturation: 0.4934422643855214
  rhythmicContrast: 0.7675738916732371
purpose: []
